name: Docker Build

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code Manually
        run: |
          git config --global init.defaultBranch main
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch --depth=1 origin +refs/pull/${{ github.event.pull_request.number }}/merge:refs/remotes/origin/pr
            git checkout -q origin/pr
          else
            git fetch --depth=1 origin ${{ github.sha }}
            git checkout -q ${{ github.sha }}
          fi

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name custom-builder --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE="${IMAGE,,}"

          TAGS="-t $IMAGE:${GITHUB_SHA::7} -t $IMAGE:latest"

          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAGS="$TAGS -t $IMAGE:${GITHUB_REF#refs/tags/v}"
          fi

          PUSH_FLAG=""
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            PUSH_FLAG="--push"
          fi

          docker buildx build \
            $TAGS \
            -f Dockerfile.prod \
            $PUSH_FLAG \
            --cache-from=type=registry,ref=$IMAGE:cache \
            --cache-to=type=registry,ref=$IMAGE:cache,mode=max \
            .
